### ISSUE TITLE
Thoughts on recommendation to use typescript enums

### ISSUE THREAD

**Issue by tylersayshi** [romgrk/blog-romgrk#5]
So I read [your post on optimizing js](https://github.com/romgrk/blog-romgrk/blob/master/src/content/posts/optimizing-javascript.tsx) a while back and came across something that motivated me to reach out wrt the recommendation to reach for ts enums as an optimization.

As your examples show, int comparison provides a clear enhancement. The thing I wanted to call out though is that the transpiled representation of enums is not exactly what is shown in the comparison example. This can be valid for the sake of simplicity of the example, but feels worth considering to me.

If you look at the output on the typescript playground you see the following:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/49338482-d2fb-49df-8d9e-ddb43d87da8b">

This expands out to be:

```js
const POSITIONS = {
  TOP: 0,
  0: 'TOP',
  BOTTOM: 1,
  1: 'BOTTOM'
}
```

[ts play link](https://www.typescriptlang.org/play/?#code/KYOwrgtgBACg9gZwJYBclxFA3gKClAFQHkYAaPKAISIOIFlyBfIA)

If the size of the enum is small and the number of comparisons are large, the recommendation you made could literally just be the exact same. So, I don't think there is really anything to change about the recommendation, but hopefully you find this interesting 😅

**Comment by romgrk** [comment]
Hey 👋  thanks for the feedback. I was already aware of what TS expands enum to but it doesn't affect the performance, so it didn't feel worth it to mention it.

Besides the JIT process could remove the keyed access altogether. The engine would typically compile `if (position === Position.TOP) { ... }` to just `if (position === 0) { ... }`, and install a "fuse" (using firefox terminology) that would trigger a deoptimization of all the functions that have assumed `Position` to be constant if ever it were changed.
